version: 2.1

executors:
  java-11:
    docker:
      - image: circleci/openjdk:11-jdk

orbs:
  gradle: circleci/gradle@2.1.0
  docker: circleci/docker@1.0.1
  owasp: entur/owasp@0.0.10

aliases:
  - &test-command |
    ./gradlew --no-daemon test jacocoTestReport sonarqube \
    -Dsonar.projectKey=enturas_$CIRCLE_PROJECT_REPONAME \
    -Dsonar.organization=$SONAR_ORG -Dsonar.projectName=$CIRCLE_PROJECT_REPONAME \
    -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$ENTUR_SONAR_PASSWORD

jobs:
  build:
    executor: java-11
    steps:
      - checkout
      - gradle/with_cache:
          steps:
            - run: ./gradlew --no-daemon clean build compileTestKotlin compileTestJava processTestResources -x test
      - persist_to_workspace:
          root: "."
          paths:
            - "*"
  test:
    executor: java-11
    steps:
      - attach_workspace:
          at: "."
      - gradle/with_cache:
          steps:
            - run:
                command: *test-command
                no_output_timeout: 30m
            - store_test_results:
                path: ./test-results/
      - persist_to_workspace:
          root: "."
          paths:
            - "*"
      - store_artifacts:
          path: ./build/reports/tests/test
      - store_test_results:
          path: ./build/test-results/test/


workflows:
  Build-Publish:
    jobs:
      - build
      - test:
          requires:
            - build
      - docker/publish:
          name: release
          registry: $DOCKER_REGISTRY
          image: $CIRCLE_PROJECT_REPONAME
          tag: $VERSION
          deploy: true
          context: global
          after_checkout:
            - attach_workspace:
                at: .
          before_build:
            - checkout
            - run: echo "export VERSION=$(echo ${CIRCLE_BRANCH}-$(date '+%Y-%m-%d-%H%M')-${CIRCLE_SHA1:0:7}-${CIRCLE_WORKFLOW_ID:0:4} | tr '/' '.' )" >> $BASH_ENV
            - run:
                name: Tag git commit with build version and push to github
                command: |
                  git config --global push.default simple
                  git config --global user.email "circleci@entur.no"
                  git config --global user.name "circleci"
                  echo $VERSION
                  git tag $VERSION
                  git push origin $VERSION
          requires:
            - test

      - owasp/owasp_dependency_check:
          executor: java-11
