{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
data:
  environmentHost: {{ .Values.ingress.host }}
metadata:
  labels:
    {{- include "common.labels" . | indent 4 }}
  annotations:
    kubernetes.io/ingress.class: traefik
    external-dns.alpha.kubernetes.io/target: {{ .Values.ingress.loadBalancerIp }}
  name: {{ template "name.name" . }}
  namespace: {{ .Values.namespace }}
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - backend:
          serviceName: {{ template "name.name" . }}
          servicePort: {{ .Values.service.externalPort }}
{{- end }}