{{- if .Values.rbac.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "name.name" . }}
  labels:
    {{- include "common.labels" . | indent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ template "name.name" . }}
  namespace: {{ .Values.namespace }}
  labels: 
    {{- include "common.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "name.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "name.name" . }}
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ template "name.name" . }}
  namespace: {{ .Values.namespace }}
  labels: 
    {{- include "common.labels" . | indent 4 }}
rules:
{{- if .Values.rbac.enabled }}
{{- ( tpl (toYaml .Values.rbac.rules) . | nindent 0 ) }}
{{- end }}
{{- end }}